### ISSUE TITLE
If EXCLUDE_PATTERNS is not set, the repository you want to subscribe is also excluded

### ISSUE THREAD

**Issue by 00Masato** [azu/watch-rss#4]
## overview
If `EXCLUDE_PATTERNS` is not set, the repository you want to subscribe is also excluded.

## cause
If `EXCLUDE_PATTERNS` is not set, `excludePatterns` is `Array[""]`, so https://github.com/azu/watch-rss/blob/master/src/add-subscription-to-inoreader.ts#L146 is determined to be true.

May I fix it and submit PR?

**Comment by azu** [comment]
Yes. welcome to PR
